### PR TITLE
upgrade pyparsing, tested with poshdeob

### PR DESCRIPTION
**Pull request by doomedraven**
hello I have just upgraded to 2.4.7 and tested the code that you left inside of that module, everything gives the same result

### CODE REVIEW

**Comment by DC3-DCCI** [comment]
Our internal testing has found issues with 2.4.7 resulting in doctests within poshdeob on lines 24 and 35.  As such this cannot be merged currently.

https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP/blob/master/mwcp/utils/poshdeob.py#L24

**Comment by doomedraven** [comment]
do you have some specific hash to test? im happy to fix this
```
python3
Python 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import pyparsing as pp
>>> pp.__version__
'2.4.7'

>>> from mwcp.utils import poshdeob
>>> deobfuscated, strings = poshdeob.deobfuscate('''\
...     ${iP} = ("{0}{2}{6}{3}{5}{4}{1}" -f'htt','8000','p://192.1','.','0:','10','68.200')
...     ${m} = ("{1}{0}{2}"-f'VsbG8','aG','=')
...     ${r} = (('@*'+'{1'+'}(){0}['+'_')-f [ChaR]124,[ChaR]36)
...     ${P} = ((("{1}{4}{3}{2}{0}"-f 'e{0}','HK','twar','Sof','CU:{0}'))  -f [cHAR]92)
...     ${S} = ((("{0}{3}{2}{4}{1}"-f'HKL','Y5a',':Y5aSoftwa','M','re'))  -CrepLAcE ([CHar]89+[CHar]53+[CHar]97),[CHar]92)
...     ${data} = '%1101000T1100101<1101100<1101100&1101111'-spLIT 'U'-sPlit 'T'-SPliT'%'-spLiT'j' -sPLIT'&' -SpLiT '<'
...     ${data2} = 'G1101000N1100101m1101100%1101100E1101111'.split( '>G{m:%~NqE')
...     ${secret} = $ShELlID[1]+$shelLiD[13]+'x'
...     ''')

>>> print(deobfuscated)
    ${iP} = 'http://192.168.200.100:8000'
    ${m} = 'aGVsbG8='
    ${r} = '@*$()|[_'
    ${P} = 'HKCU:\Software\'
    ${S} = ('HKLM:Y5aSoftwareY5a'  -CrepLAcE 'Y5a','\')
    ${data} = ('', '1101000', '1100101', '1101100', '1101100', '1101111')
    ${data2} = ('', '1101000', '1100101', '1101100', '1101100', '1101111')
    ${secret} = 'iex'

>>> strings
['http://192.168.200.100:8000', 'aGVsbG8=', '@*$()|[_', 'HKCU:\\Software\\', 'HKLM:Y5aSoftwareY5a', 'Y5a', '\\', '', '1101000', '1100101', '1101100', '1101100', '1101111', '', '1101000', '1100101', '1101100', '1101100', '1101111', 'iex']
>>>
``

**Comment by DC3-DCCI** [comment]
If you take a look at a diff from the previous results you will notice some differences including with the results of the HKLM path caused by changes to the library.

**Comment by doomedraven** [comment]
ah ok i didn't spot it before, ok i will come with solution as i walked all their releases since 2.3.0 to see what changed so i will provide the proper upgrade, i will push to the same branch

**Comment by doomedraven** [comment]
maybe you can help me here, the problem is here, any idea why? im new to pyparsing, so is taking me more than someone that is more familiar, but i will get to that if no ;) 
```
#(pp.Combine("-" + _replace_command) + concat_string("old") + "," + concat_string("new"))
"-CrepLAcE" + concat_string("old") + "," + concat_string("new")
```

if i replace that line like that, it works just fine

**Comment by doomedraven** [comment]
ok i wasn't able to fix that so i have opened them an issue, so if they help to fix that i will bring the fix here https://github.com/pyparsing/pyparsing/issues/289, let it open few days if they won't respond, i will close this

**Comment by doomedraven** [comment]
Screenshot 2021-06-27 at 19 42 16

So based on the answer what do you think if we use it next example? I saw your comment about space between `c` and replace
```
_replace_command = pp.CaselessKeyword("creplace")("command") | pp.CaselessKeyword("replace")("command")
```

tested that with latest version and works just fine

**Comment by DC3-DCCI** [comment]
Upon closer inspection, using `CaselessKeyword` was inappopriate in the first place since there can be non-whitespace characters around the replace command such as `-` or `(`. Changing `CaselessKeyword` to `CaselessLiteral` fixes this issue and tests work with both the old and newer version pyparsing.

We went ahead and updated poshdeob and removed the pinning for pyparsing in the most recent minor release 3.3.1.

Thanks for looking into this.

**Comment by doomedraven** [comment]
thanks for updating

**Pull request closed without merging**
